### PR TITLE
Calm deposit other than usdc

### PR DESCRIPTION
**Pull request by jihoonsong**
- Airdrop all possible deposit tokens before deploy contracts.
  - Currently, wAVAX and USDC are supported for Avalanche, and wETH, ARB, and USDC are supported for Arbitrum.
  - Whenever we want to have a new deposit token, we need to add its info to test/helper/addresses.ts/WhaleAdddrs.ts
- Limit maximum deposit token balance of each user to 100.
- Extending index to receive any ERC20 is out of scope.
- Opt out old tests of portfolios and strategies.
  - I don't know what is a plan for these so opted out them.

### CODE REVIEW

**Comment by ferencdg** [comment]
Can you please explain why the tests for existing portfolios and strategies were commented out? We plan to keep supporting those old strategies.

**Comment by jihoonsong** [comment]
Old ones' portfolios don't have `getDepositToken`, which is necessary to figure out which token is used for deposit. You can add the function to portfolios of old ones and opt-in them again.

**Comment by ferencdg** [comment]
> Old ones' portfolios don't have `getDepositToken`, which is necessary to figure out which token is used for deposit. You can add the function to portfolios of old ones and opt-in them again.

I don't understand that old portfolios don't have 'getDepositToken': https://github.com/BrokkrFinance/bro-strategies/blob/4517f95745c1e60bf296d4aad56915ee50af1941/contracts/oracleBasedFramework/bases/portfolio/PortfolioBaseUpgradeable.sol#L356

Also strategies like the MockStrategy is also commented out

**Comment by jihoonsong** [comment]
Screenshot 2023-07-26 at 5 05 05 PM
Apparently not all of them.

**Comment by ferencdg** [comment]
> Screenshot 2023-07-26 at 5 05 05 PM Apparently not all of them.

getDepositToken is part of IInvestable, so all portfolio and strategies should support it. Can you please find out the rootcause why those tests fails? We cannot decommision strategies like the Cash that we continue to use in production.

**Comment by ferencdg** [comment]
> > Screenshot 2023-07-26 at 5 05 05 PM Apparently not all of them.
> 
> getDepositToken is part of IInvestable, so all portfolio and strategies should support it. Can you please find out the rootcause why those tests fails? We cannot decommision strategies like the Cash that we continue to use in production.

this is a live Cash strategy with getDepositToken https://snowtrace.io/address/0xcc23fa2a377Ea6F43E34A8c43d08DC428B647a81#readProxyContract

**Comment by jihoonsong** [comment]
I think I helped you enough with your task Daniel.

**Comment by ferencdg** [comment]
it was a bug in the PR:

await this.portfolio.getDepositToken()

should be changed to

await this.strategy.getDepositToken()

**Pull request merged**
